// dATA FLOW
export const READ_CSV = "READ_CSV";
export const READ_CSV_ERROR = "READ_CSV_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
export const EDIT_DATA = "EDIT_DATA";
export const SELF_INPUT_DATA = "SELF_INPUT_DATA";
export const ADD_YEAR_COUNTRY = "ADD_YEAR_COUNTRY";
export const ADD_ROW_COUNTRY = "ADD_ROW_COUNTRY";
export const DELETE_YEAR_COUNTRY = "DELETE_YEAR_COUNTRY";
export const DELETE_ROW_COUNTRY = "DELETE_ROW_COUNTRY";

// UI
export const OPTIONS_UI_TWO_LEVEL = "OPTIONS_UI_TWO_LEVEL";
export const OPTIONS_UI_ONE_LEVEL = "OPTIONS_UI_ONE_LEVEL";
