// dATA FLOW
export const READ_CSV = "READ_CSV";
export const READ_CSV_ERROR = "READ_CSV_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
export const EDIT_DATA = "EDIT_DATA";
export const SELF_INPUT_DATA_COUNTRY = "SELF_INPUT_DATA_COUNTRY";
export const ADD_YEAR_COUNTRY = "ADD_YEAR_COUNTRY";
export const ADD_ROW_COUNTRY = "ADD_ROW_COUNTRY";
export const DELETE_YEAR_COUNTRY = "DELETE_YEAR_COUNTRY";
export const DELETE_ROW_COUNTRY = "DELETE_ROW_COUNTRY";
// world data
export const READ_CSV_WORLD_DATA = "READ_CSV_WORLD_DATA";
export const ADD_YEAR_WORLD_DATA = "ADD_YEAR_WORLD_DATA";
export const ADD_ROW_WORLD_DATA = "ADD_ROW_WORLD_DATA";
export const DELETE_YEAR_WORLD_DATA = "DELETE_YEAR_WORLD_DATA";
export const EDIT_WORLD_DATA = "EDIT_WORLD_DATA";
export const SELF_INPUT_DATA_WORLD = "SELF_INPUT_DATA_WORLD";

// FOR THE LIST OF YEAR
export const UPDATE_FIRST_YEAR = "UPDATE_FIRST_YEAR";
export const UPDATE_SECOND_YEAR = "UPDATE_SECOND_YEAR";
export const ALL_YEARS = "ALL_YEARS";
export const RESET_YEARS = "RESET_YEARS";
export const REMOVE_YEAR_ALL_YEARS = "REMOVE_YEAR_ALL_YEARS";

// UI
export const OPTIONS_UI_TWO_LEVEL = "OPTIONS_UI_TWO_LEVEL";
export const OPTIONS_UI_ONE_LEVEL = "OPTIONS_UI_ONE_LEVEL";
